### ISSUE TITLE
Use releases as changelogs

### ISSUE THREAD

**Issue by nanoxd** [ashfurrow/Action#9]
Thanks for putting the effort into this 😀.

I see that currently [Changelog.md](https://github.com/ashfurrow/Action/blob/master/Changelog.md) is used to track changes. Since tags are also being used, could the same data be put into the releases tab? That way, it would make it easy for users to know where to go to without looking for the changelog file. Similar to [RxSwift](https://github.com/ReactiveX/RxSwift/releases)

![](http://media3.giphy.com/media/5xJIIRPC23yZG/giphy.gif)

**Comment by orta** [comment]
It's obviously not a binary decision, but the CHANGELOG ideally should be canonical here. At CocoaPods we use a script to generate the Release notes for a specific build.

**Comment by ashfurrow** [comment]
Yeah, once we get to a larger scale (probably around our 1.0), we should automate releases. GitHub's "Releases" vs "Tags" thing has always confused me, but we can definitely add release notes to the tags.

**Comment by nanoxd** [comment]
Agreed, I don't mean that practices should change, it would be cool to have both 😀. Thanks!

**Comment by nanoxd** [comment]
Touching back on this, I've added a release for the 1.0.0 release. It's a direct copy of the changelog for now. One of the cool things with this approach is that any watchers are notified of a new release with the changelog

**Comment by ashfurrow** [comment]
That's cool. I keep forgetting to do a release, since it matters for Carthage (which is really silly imo). But letting watchers know is :+1:
